@startuml ゆで卵を作る
start
fork
  :銀行で金をおろす\n作業時間10分;
  :スーパーで卵を買う\n作業時間10分;
fork again
  :お湯を沸かす\n作業時間20分;
end fork 
fork
 :卵を洗う\n作業時間10分;
 :お湯を沸かす\n作業時間10分;
 :卵をゆでる\n作業時間10分;
fork again
 :腹筋をして腹を減らす30分;
end fork 
 :殻を割る;
 :塩を振る;
stop

@enduml
